{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  CONFIG_API_URL: {{ .Values.api.config }}
  GITLAB_API_URL: {{ .Values.api.gitlab }}
  GITLAB_TOKEN: {{ .Values.tokens.gitlab }}
  DATABASE_SERVICE_NAME: "{{ .Values.db.mongodbServiceName }}"
  MONGODB_USER: "{{ .Values.db.mongodbUser }}"
  MONGODB_PASSWORD: "{{ .Values.db.mongodbPassword }}"
  MONGODB_DATABASE: "{{ .Values.db.mongodbDatabase }}"
  MONGODB_ADMIN_PASSWORD: "{{ .Values.db.mongodbAdminPassword }}"
  ENGAGEMENTS_REPOSITORY_ID: "{{ .Values.gitlab.engagementRepositoryId }}"
  DEPLOY_KEY: "{{ .Values.gitlab.deployKey }}"

{{- end }}
