name: lodestar-engagements
development: true

imageName: "lodestar-engagements"
imageTag: "latest"

builderImage: registry.access.redhat.com/ubi8/openjdk-11
builderImageTag: 1.3

servicePort: 8080

db:
  mongodbServiceName: lodestar-engagements-mongodb
  mongodbUser: mongouser
  mongodbPassword: mongopassword
  mongodbDatabase: engagements
  mongodbAdminPassword: mongoadminpassword

git:
  uri: https://github.com/rht-labs/lodestar-engagements.git
  ref: main

api:
  gitlab: http://gitlab.com
  config: http://lodestar-config:8080
  participants: http://lodestar-participants:8080

tokens:
  gitlab: nope

gitlab:
  deployKey: nope
  engagementRepositoryId: -1
